name: multi-translator-unifier-stack

services:
    mtu:
        stdin_open: true
        tty: true
        container_name: multi-translator
        ports:
            - 8192:8192
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 163453
            MYSQL_HOST: 192.168.2.5
            MYSQL_PORT: 3306
            MYSQL_DBNAME: translate
            REDIS_HOST: multi-translator-redis
            REDIS_PORT: 6380
            REDIS_PASSWORD: 163453
            REDIS_DB: 1
        volumes:
            - go_data:/log
            - ./:/data
        image: zhangyiming748/translate:latest
        command: go run /app/main.go
    redis:
        image: redis:8.0-M03-alpine3.21
        container_name: multi-translator-redis
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf # 假设您有这个配置文件
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        restart: unless-stopped

volumes:
    redis_data:
    go_data:
