name: multi-translator-unifier-stack

services:
    mtu:
        stdin_open: true
        tty: true
        container_name: trans
        ports:
            - 8192:8192
        volumes:
            - go_data:/log
        image: zhangyiming748/translate
        command: go run /app/main.go
        # docker run -dit --rm --name trans -v C:\Users\zen\Github\MultiTranslatorUnifier:/data -p 8192:8192  zhangyiming748/translate ash
    redis:
        image: redis:8.0-M03-alpine3.21
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf # 假设您有这个配置文件
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        restart: unless-stopped

    mysql:
        image: mysql:9.2.0
        container_name: mysql # 修正了 container_name
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - "3306:3306"
        restart: unless-stopped

volumes:
    redis_data:
    mysql_data:
    go_data:
