name: multi-translator-unifier-stack

services:
    mtu:
        stdin_open: true
        tty: true
        container_name: multi-translator
        ports:
            - 8192:8192
        volumes:
            - ./:/data
        image: zhangyiming748/translate:latest
