name: multi-translator-unifier-stack

services:
  mtu:
    container_name: mtu
    image: zhangyiming748/multi_translator_unifier
    volumes:
      - go_data:/log
    environment:
      - LINUXD=33
    depends_on: # 确保 mtu 在 redis 和 mysql 之后启动
      - redis
      - mysql
    

  redis:
    image: redis:8.0-M03-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf # 假设您有这个配置文件
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    restart: always
    

  mysql:
    image: mysql:9.2.0
    container_name: mysql # 修正了 container_name
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    restart: always
   

volumes:
  redis_data:
  mysql_data:
  go_data: