name: multi-translator-unifier-stack

services:
    mtu:
        stdin_open: true
        tty: true
        container_name: multi-translator
        ports:
            - 8192:8192
        volumes:
            - ./:/data
        image: zhangyiming748/translate:latest
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=163453
            - MYSQL_HOST=192.168.2.10
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=translate
            - LINUXDO=1
            - PROXY=192.168.2.10:8889
